apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: arr-stack
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - service: radarr
      - service: sonarr
      - service: lidarr
      - service: readarr
      - service: bazarr
  template:
    metadata:
      name: '{{service}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/poiley/rinzler.git
        targetRevision: HEAD
        path: 'k8s/arr-stack/{{service}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: arr-stack
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true