apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: download
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - service: gluetun-transmission
      - service: jackett
      - service: flaresolverr
      - service: mylar
      - service: fmd2
  template:
    metadata:
      name: '{{service}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/poiley/rinzler.git
        targetRevision: HEAD
        path: 'k8s/download/{{service}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: download
      syncPolicy:
        syncOptions:
        - CreateNamespace=true