apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: network-services
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - service: pihole
      - service: samba
  template:
    metadata:
      name: '{{service}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/poiley/rinzler.git
        targetRevision: HEAD
        path: 'k8s/network-services/{{service}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: network-services
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true