unifi:
  username: ""
  password: ""
  api_key: ""

pihole:
  password: ""
  api_token: ""

github:
  token: ""
  runner_token: ""
  ssh:
    private_key: ""

dev:
  server:
    ssh_private_key: ""

bootstrap:
  basic_auth_header: ""
  wireguard:
    private_key: ""
    addresses: "" 