apiVersion: v1
kind: Service
metadata:
  name: samba
  namespace: network-services
spec:
  type: LoadBalancer
  selector:
    app: samba
  ports:
  - name: netbios-ssn
    port: 139
    targetPort: 139
  - name: microsoft-ds
    port: 445
    targetPort: 445
  loadBalancerIP: 192.168.1.227