services:
  dockge:
    image: louislam/dockge:1.4.2
    container_name: dockge
    restart: unless-stopped
    ports:
      - 5001:5001
    environment:
      - DOCKGE_STACKS_DIR=${DOCKGE_STACKS_DIR}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./compose:/stacks
      - /storage/dockge/data:/data 