apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  # Node Exporter
  - node-exporter.yaml
  
  # Tautulli Exporter
  - tautulli-exporter.yaml
  
  # Exportarr instances
  - exportarr-radarr.yaml
  - exportarr-sonarr.yaml
  - exportarr-lidarr.yaml
  - exportarr-bazarr.yaml