# TEMPLATE FILE - DO NOT APPLY DIRECTLY
# Copy this file and replace placeholder values before applying
#
# To create the actual secret:
# kubectl create secret generic arr-config-secrets \
#   --from-literal=jackett-api-key="YOUR_JACKETT_API_KEY" \
#   --from-literal=transmission-username="YOUR_USERNAME" \
#   --from-literal=transmission-password="YOUR_PASSWORD" \
#   --namespace arr-stack
#
apiVersion: v1
kind: Secret
metadata:
  name: arr-config-secrets
  namespace: arr-stack
type: Opaque
stringData:
  jackett-api-key: "REPLACE_WITH_JACKETT_API_KEY"
  transmission-username: "REPLACE_WITH_USERNAME"
  transmission-password: "REPLACE_WITH_PASSWORD"