apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media

resources:
  # Plex
  - plex/deployment.yaml
  - plex/service.yaml
  - plex/ingress.yaml
  # Tautulli
  - tautulli/deployment.yaml
  - tautulli/service.yaml
  - tautulli/ingress.yaml
  # Kavita
  - kavita/deployment.yaml
  - kavita/service.yaml
  - kavita/ingress.yaml