apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolverr
  namespace: download
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaresolverr
  template:
    metadata:
      labels:
        app: flaresolverr
    spec:
      nodeSelector:
        kubernetes.io/hostname: rinzler
      containers:
      - name: flaresolverr
        image: 21hsmw/flaresolverr:nodriver
        env:
        - name: LOG_LEVEL
          value: "info"
        - name: LOG_HTML
          value: "false"
        - name: CAPTCHA_SOLVER
          value: "none"
        - name: TZ
          value: "America/Los_Angeles"
        - name: DRIVER
          value: "nodriver"
        ports:
        - containerPort: 8191
          name: http
        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi