apiVersion: v1
kind: ConfigMap
metadata:
  name: autokuma-monitors
  namespace: monitoring
data:
  # AutoKuma will read all .json files from the static monitors directory
  infrastructure.json: |
    {
      "http": {
        "name": "ArgoCD Server",
        "url": "http://argocd-server.argocd.svc.cluster.local:80",
        "interval": 60,
        "retry_interval": 20,
        "max_retries": 3,
        "accepted_statuscodes": "200-302"
      }
    }
  
  argocd-external.json: |
    {
      "http": {
        "name": "ArgoCD External",
        "url": "https://argocd.rinzler.cloud",
        "interval": 300,
        "retry_interval": 60,
        "max_retries": 3,
        "accepted_statuscodes": "200-302"
      }
    }
  
  traefik.json: |
    {
      "http": {
        "name": "Traefik Dashboard",
        "url": "https://traefik.rinzler.cloud",
        "interval": 300,
        "retry_interval": 60,
        "max_retries": 3
      }
    }
  
  prometheus.json: |
    {
      "http": {
        "name": "Prometheus",
        "url": "http://prometheus.monitoring.svc.cluster.local:9090/-/healthy",
        "interval": 60,
        "retry_interval": 20,
        "max_retries": 3
      }
    }
  
  grafana.json: |
    {
      "http": {
        "name": "Grafana",
        "url": "http://grafana.monitoring.svc.cluster.local:3000",
        "interval": 60,
        "retry_interval": 20,
        "max_retries": 3
      }
    }
  
  grafana-external.json: |
    {
      "http": {
        "name": "Grafana External",
        "url": "https://grafana.rinzler.cloud",
        "interval": 300,
        "retry_interval": 60,
        "max_retries": 3
      }
    }
  
  plex.json: |
    {
      "http": {
        "name": "Plex",
        "url": "http://plex.media.svc.cluster.local:32400/web",
        "interval": 60,
        "retry_interval": 20,
        "max_retries": 3
      }
    }
  
  plex-external.json: |
    {
      "http": {
        "name": "Plex External",
        "url": "https://plex.rinzler.cloud",
        "interval": 300,
        "retry_interval": 60,
        "max_retries": 3
      }
    }
  
  sonarr.json: |
    {
      "http": {
        "name": "Sonarr",
        "url": "http://sonarr.arr-stack.svc.cluster.local:8989",
        "interval": 60,
        "retry_interval": 20,
        "max_retries": 3
      }
    }
  
  sonarr-external.json: |
    {
      "http": {
        "name": "Sonarr External",
        "url": "https://sonarr.rinzler.cloud",
        "interval": 300,
        "retry_interval": 60,
        "max_retries": 3
      }
    }
  
  radarr.json: |
    {
      "http": {
        "name": "Radarr",
        "url": "http://radarr.arr-stack.svc.cluster.local:7878",
        "interval": 60,
        "retry_interval": 20,
        "max_retries": 3
      }
    }
  
  radarr-external.json: |
    {
      "http": {
        "name": "Radarr External",
        "url": "https://radarr.rinzler.cloud",
        "interval": 300,
        "retry_interval": 60,
        "max_retries": 3
      }
    }
  
  jackett.json: |
    {
      "http": {
        "name": "Jackett",
        "url": "http://jackett.download.svc.cluster.local:9117",
        "interval": 60,
        "retry_interval": 20,
        "max_retries": 3
      }
    }
  
  pihole.json: |
    {
      "http": {
        "name": "PiHole",
        "url": "http://pihole.network-services.svc.cluster.local:80",
        "interval": 60,
        "retry_interval": 20,
        "max_retries": 3
      }
    }