apiVersion: apps/v1
kind: Deployment
metadata:
  name: autokuma
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autokuma
  template:
    metadata:
      labels:
        app: autokuma
    spec:
      initContainers:
      - name: wait-for-uptime-kuma
        image: busybox:1.36
        command:
        - sh
        - -c
        - |
          echo "Waiting for Uptime Kuma to be ready..."
          for i in $(seq 1 60); do
            if nc -z uptime-kuma 3001; then
              echo "Uptime Kuma is ready!"
              exit 0
            fi
            echo "Attempt $i/60: Uptime Kuma not ready yet..."
            sleep 5
          done
          echo "Timeout waiting for Uptime Kuma"
          exit 1
      containers:
      - name: autokuma
        image: ghcr.io/bigboot/autokuma:latest
        env:
        - name: AUTOKUMA__KUMA__URL
          value: "http://uptime-kuma:3001"
        - name: AUTOKUMA__KUMA__USERNAME
          value: "admin"
        - name: AUTOKUMA__KUMA__PASSWORD
          valueFrom:
            secretKeyRef:
              name: autokuma-secret
              key: admin-password
        - name: AUTOKUMA__STATIC_MONITORS
          value: "/monitors"
        - name: AUTOKUMA__DOCKER__ENABLED
          value: "false"
        volumeMounts:
        - name: monitors
          mountPath: /monitors
          readOnly: true
        - name: data
          mountPath: /data
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: monitors
        configMap:
          name: autokuma-monitors
      - name: data
        persistentVolumeClaim:
          claimName: autokuma-pvc