---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: autokuma
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: autokuma
rules:
- apiGroups:
  - "autokuma.bigboot.dev"
  resources:
  - kumaentities
  verbs:
  - get
  - list
  - watch
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "apps"
  resources:
  - deployments
  - statefulsets
  - daemonsets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: autokuma
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: autokuma
subjects:
- kind: ServiceAccount
  name: autokuma
  namespace: monitoring