apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-kuma
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptime-kuma
  template:
    metadata:
      labels:
        app: uptime-kuma
    spec:
      initContainers:
      - name: init-admin
        image: louislam/uptime-kuma:1.23.15
        command:
        - sh
        - -c
        - |
          set -e
          echo "Starting temporary Uptime Kuma to initialize database..."
          
          # Start Uptime Kuma in background to create database schema
          node server/server.js &
          PID=$!
          
          # Wait for database to be created
          echo "Waiting for database initialization..."
          for i in $(seq 1 30); do
            if [ -f "/app/data/kuma.db" ]; then
              # Check if user table exists
              if sqlite3 /app/data/kuma.db ".tables" 2>/dev/null | grep -q "user"; then
                echo "Database schema ready!"
                break
              fi
            fi
            echo "Waiting for database schema... ($i/30)"
            sleep 2
          done
          
          # Stop the temporary server
          kill $PID 2>/dev/null || true
          sleep 2
          
          # Now inject admin account
          echo "Creating admin account..."
          
          # Check if admin already exists
          USER_COUNT=$(sqlite3 /app/data/kuma.db "SELECT COUNT(*) FROM user WHERE username='admin';" 2>/dev/null || echo "0")
          
          if [ "$USER_COUNT" = "0" ]; then
            # Password hash for "password" (simpler for testing)
            # Hash: $2y$10$IWoZl5q9Tvvp1wxROvi4hOul7XP.rfyrvm4xbm7ufVANke1nfvLIu
            sqlite3 /app/data/kuma.db "INSERT INTO user (id, username, password, active, timezone, twofa_status) VALUES (1, 'admin', '\$2y\$10\$IWoZl5q9Tvvp1wxROvi4hOul7XP.rfyrvm4xbm7ufVANke1nfvLIu', 1, 'UTC', 0);" || true
            echo "Admin account created successfully!"
          else
            echo "Admin account already exists"
          fi
          
          echo "Initialization complete"
        volumeMounts:
        - name: data
          mountPath: /app/data
      containers:
      - name: uptime-kuma
        image: louislam/uptime-kuma:1.23.15
        ports:
        - containerPort: 3001
          name: http
        env:
        - name: UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN
          value: "true"
        - name: TZ
          value: "America/New_York"
        volumeMounts:
        - name: data
          mountPath: /app/data
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: uptime-kuma-pvc