apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-issuers
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/poiley/rinzler
    targetRevision: HEAD
    path: k8s/cert-manager/issuers
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true