---
# Self-signed issuer for bootstrapping the CA
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
# CA Certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rinzler-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: rinzler-ca
  secretName: rinzler-ca-secret
  duration: 87600h # 10 years
  renewBefore: 720h # 30 days
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
# Main CA Issuer for all services
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: rinzler-ca-issuer
spec:
  ca:
    secretName: rinzler-ca-secret