apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-data
  namespace: network-services
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: network-services
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      nodeSelector:
        kubernetes.io/hostname: rinzler
      containers:
      - name: pihole
        image: pihole/pihole:2025.07.1
        imagePullPolicy: IfNotPresent
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - CAP_CHOWN
            - CAP_SYS_TIME
            - CAP_NET_BIND_SERVICE
            - CAP_NET_RAW
        env:
        - name: TZ
          value: "America/Los_Angeles"
        - name: WEBPASSWORD
          value: "Dr1v30861197"
        - name: PIHOLE_DNS_
          value: "1.1.1.1;1.0.0.1"
        - name: DNSSEC
          value: "false"
        - name: DNSMASQ_LISTENING
          value: "all"
        - name: FTLCONF_dns_listeningMode
          value: "all"
        - name: VIRTUAL_HOST
          value: "pihole.rinzler.grid"
        - name: PROXY_LOCATION
          value: "pihole"
        - name: FTLCONF_dns_interface
          value: "eth0"
        - name: FTLCONF_database_network_parseARPcache
          value: "true"
        - name: FTLCONF_dns_reply_host_IPv4
          value: "192.168.1.227"
        - name: PIHOLE_INTERFACE
          value: "eth0"
        - name: IPV4_ADDRESS
          value: "192.168.1.227/24"
        - name: WEB_PORT
          value: "80"
        ports:
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        - containerPort: 53
          name: dns-udp
          protocol: UDP
        - containerPort: 80
          name: web
        - containerPort: 443
          name: web-ssl
        volumeMounts:
        - name: pihole-data
          mountPath: /etc/pihole
          subPath: pihole
        - name: pihole-data
          mountPath: /etc/dnsmasq.d
          subPath: dnsmasq
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /admin/
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /admin/
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: pihole-data
        persistentVolumeClaim:
          claimName: pihole-data
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-dns
  namespace: network-services
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.227
  externalTrafficPolicy: Local
  ports:
  - name: dns-tcp
    port: 53
    targetPort: 53
    protocol: TCP
  - name: dns-udp
    port: 53
    targetPort: 53
    protocol: UDP
  selector:
    app: pihole
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-web
  namespace: network-services
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 80
    targetPort: 80
  - name: web-ssl
    port: 443
    targetPort: 443
  selector:
    app: pihole