apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: network-services
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      nodeSelector:
        kubernetes.io/hostname: rinzler
      initContainers:
      - name: copy-configs
        image: busybox:latest
        command: ['sh', '-c', 'cp /config/* /etc-dnsmasq/ 2>/dev/null || true']
        volumeMounts:
        - name: dnsmasq-config
          mountPath: /config
        - name: etc-dnsmasq
          mountPath: /etc-dnsmasq
      containers:
      - name: pihole
        image: pihole/pihole:latest
        env:
        - name: TZ
          value: "America/Los_Angeles"
        - name: WEBPASSWORD
          valueFrom:
            secretKeyRef:
              name: pihole-secret
              key: webpassword
        - name: RATE_LIMIT
          value: "0/0"  # From .env.example
        - name: PIHOLE_DNS_
          value: "8.8.8.8;8.8.4.4"
        - name: FTLCONF_misc_etc_dnsmasq_d
          value: "true"
        ports:
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        - containerPort: 53
          name: dns-udp
          protocol: UDP
        - containerPort: 80
          name: web
        volumeMounts:
        - name: etc-pihole
          mountPath: /etc/pihole
        - name: etc-dnsmasq
          mountPath: /etc/dnsmasq.d
        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /admin/
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /admin/
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: etc-pihole
        hostPath:
          path: /storage/docker_volumes/pihole/etc-pihole
          type: Directory
      - name: etc-dnsmasq
        hostPath:
          path: /storage/docker_volumes/pihole/etc-dnsmasq.d
          type: Directory
      - name: dnsmasq-config
        configMap:
          name: pihole-dnsmasq