apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pihole
  namespace: network-services
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: pihole.rinzler.grid
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pihole-web
            port:
              number: 8081
