version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - sonarr_data:/config
      - /storage/media:/media
      - /storage/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
        
volumes:
  sonarr_data: