version: "2.1"
services:
  deluge:
    image: lscr.io/linuxserver/deluge
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - deluge_data:/config
      - /storage/downloads:/downloads
      - /storage/media:/media
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    network_mode: container:mullvad
    restart: unless-stopped

volumes:
  deluge_data:

---
version: "2"
services:
  openvpn-client:
    image: yacht7/openvpn-client
    container_name: mullvad
    cap_add:
      - NET_ADMIN
    environment: 
      - KILL_SWITCH=on
      - FORWARDED_PORTS=58846
      - SUBNETS=192.168.0.0/24,192.168.1.0/24
    devices:
      - /dev/net/tun                      
    volumes:
      - /storage/docker_volumes/vpn:/data/vpn   
    ports:
      - 58846:58846
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
  restart: unless-stopped