version: "2.1"
services:
  bazarr:
    image: lscr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /bazarr_data:/config
      - /storage/media/movies:/movies #optional
      - /storage/media/tv:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped
    
volumes:
  bazarr_data: