version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - radarr_data:/config
      - /storage/media:/media
      - /storage/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    
volumes:
  radarr_data:
