apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-mcp-server-config
  namespace: mcp-servers
data:
  security_config.yaml: |
    # Security configuration for k8s-mcp-server
    allowed_commands:
      - kubectl
      - helm
      - argocd
    forbidden_args:
      - "--token"
      - "--kubeconfig"
    max_command_length: 1000