apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-mcp-server
  namespace: mcp-servers
  labels:
    app: k8s-mcp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-mcp-server
  template:
    metadata:
      labels:
        app: k8s-mcp-server
    spec:
      serviceAccountName: k8s-mcp-server
      containers:
      - name: k8s-mcp-server
        image: ghcr.io/alexei-led/k8s-mcp-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: MCP_SERVER_PORT
          value: "8080"
        - name: ALLOWED_COMMANDS
          value: "kubectl,helm,argocd"
        - name: LOG_LEVEL
          value: "info"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: config
          mountPath: /app
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: k8s-mcp-server-config