global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'docker'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:9323']  # Docker metrics endpoint

  - job_name: 'containers'
    metrics_path: '/metrics'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 15s
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex: '/(.*)'
        target_label: container_name
        replacement: '$1'
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: service_name 