runner:
  # GitHub Configuration
  github:
    owner: "poiley"
    repo_name: "rinzler"
    ssh:
      user: "poile"
      server_host: "rinzler.lan"

  # Runner Configuration
  name: "rinzler-runner"
  dir: "/opt/github-runner"
  version: "2.314.1"
  hash: "f4c3af8df563b5a16ea14aba6c13c5c23b5d78a1" 