services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - SONARR__AUTHENTICATION_METHOD=1
    volumes:
      - sonarr_data:/config
      - /storage/media:/media
      - /storage/downloads:/downloads
    networks:
      - proxy 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=PathPrefix(`/sonarr`)"
      - "traefik.http.routers.sonarr.entrypoints=web"
      - "traefik.http.middlewares.sonarr-auth.headers.customrequestheaders.Authorization=${BASIC_AUTH_HEADER}"
      - "traefik.http.middlewares.sonarr-prefix.addprefix.prefix=/sonarr"
      - "traefik.http.middlewares.sonarr-strip.stripprefix.prefixes=/sonarr"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
      - "traefik.http.routers.sonarr.middlewares=sonarr-auth@docker,sonarr-prefix@docker,sonarr-strip@docker"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8989" ]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  proxy:
    name: proxy

volumes:
  sonarr_data:
    name: sonarr_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /storage/docker/sonarr/config