version: "3.8"

services:
  dockge:
    image: louislam/dockge:1
    container_name: dockge
    restart: unless-stopped
    ports:
      - "5001:5001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - dockge_data:/app/data
      - dockge_stacks:/opt/stacks
    environment:
      - DOCKGE_STACKS_DIR=/opt/stacks
    networks:
      - default

networks:
  default:
    name: dockge
    driver: bridge

volumes:
  dockge_data:
    name: dockge_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /storage/docker/dockge/data
  dockge_stacks:
    name: dockge_stacks
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /storage/docker/dockge/stacks 