services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PLEX_MEDIA_SERVER_MAX_PLUGIN_PROCS=6
      - PLEX_MEDIA_SERVER_USER=${PLEX_MEDIA_SERVER_USER}
      - VERSION=docker
    volumes:
      - /storage/docker_volumes/plex_data/plex_data/_data:/config
      - /storage/media:/media
    ports:
      - 32400:32400
    restart: unless-stopped

volumes:
  plex_data:
    external: true 