services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PLEX_MEDIA_SERVER_MAX_PLUGIN_PROCS=6
      - PLEX_MEDIA_SERVER_USER=${PLEX_MEDIA_SERVER_USER}
      - VERSION=docker
    volumes:
      - plex_data:/config
      - /storage/media:/media
    ports:
      - 32400:32400
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:32400/web/index.html" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  plex_data:
    name: plex_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /storage/docker/plex/config 