services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    ports:
      - "8081:80/tcp"
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      TZ: ${TZ}
      WEBPASSWORD: ${PIHOLE_PASSWORD}
      RATE_LIMIT: '0/0'
    volumes:
      - pihole_etc:/etc/pihole
      - pihole_dnsmasq:/etc/dnsmasq.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/admin/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  pihole_etc:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /storage/docker/pihole/etc-pihole
  pihole_dnsmasq:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /storage/docker/pihole/etc-dnsmasq.d