services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - RADARR__URLBASE=/radarr
      - RADARR__AUTHENTICATION_METHOD=1
    volumes:
      - radarr_data:/config
      - /storage/media:/media
      - /storage/downloads:/downloads
    networks:
      - proxy
    ports:
      - 7878:7878
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=PathPrefix(`/radarr`)"
      - "traefik.http.routers.radarr.entrypoints=web"
      - "traefik.http.middlewares.radarr-auth.headers.customrequestheaders.Authorization=${BASIC_AUTH_HEADER}"
      - "traefik.http.middlewares.radarr-prefix.addprefix.prefix=/radarr"
      - "traefik.http.middlewares.radarr-strip.stripprefix.prefixes=/radarr"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
      - "traefik.http.routers.radarr.middlewares=radarr-auth@docker,radarr-prefix@docker,radarr-strip@docker"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7878/ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  radarr_data:
    name: radarr_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /storage/docker/radarr/config

networks:
  proxy:
    name: proxy