services:
  samba:
    image: dperson/samba:latest
    container_name: samba
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - SHARE=mount;/mount;yes;no;yes;all;none;none
      - WORKGROUP=WORKGROUP
    ports:
      - 139:139
      - 445:445
    volumes:
      - /storage:/mount
    restart: unless-stopped