services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - bazarr_data:/config
      - /storage/media/movies:/movies
      - /storage/media/tv:/tv
    ports:
      - 6767:6767
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6767" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  bazarr_data:
    name: bazarr_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /storage/docker/bazarr/config