services:
  flaresolverr:
    image:  21hsmw/flaresolverr:nodriver
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
      - DRIVER=nodriver
    ports:
      - 8191:8191
    restart: unless-stopped 
