apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: readarr
  namespace: arr-stack
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: readarr.rinzler.grid
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: readarr
            port:
              number: 8787
