apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  # Namespace
  - namespace.yaml
  
  # Prometheus
  - prometheus-config.yaml
  - prometheus-deployment.yaml
  
  # Grafana  
  - grafana-datasources.yaml
  - grafana-dashboards-config.yaml
  - grafana-deployment.yaml
  - grafana-ingress.yaml

# Note: Secrets are managed by apply-secrets.sh script
# - grafana-secret
# - monitoring-secrets