apiVersion: apps/v1
kind: Deployment
metadata:
  name: gluetun-transmission
  namespace: download
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: gluetun-transmission
  template:
    metadata:
      labels:
        app: gluetun-transmission
    spec:
      nodeSelector:
        kubernetes.io/hostname: rinzler
      securityContext:
        sysctls:
        - name: net.ipv4.conf.all.src_valid_mark
          value: "1"
        - name: net.ipv6.conf.all.disable_ipv6
          value: "1"
      containers:
      # Gluetun VPN container
      - name: gluetun
        image: qmcgaw/gluetun
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
              - SYS_MODULE
        env:
        - name: VPN_SERVICE_PROVIDER
          value: "mullvad"
        - name: VPN_TYPE
          value: "wireguard"
        - name: WIREGUARD_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: mullvad-secrets
              key: private-key
        - name: WIREGUARD_ADDRESSES
          valueFrom:
            secretKeyRef:
              name: mullvad-secrets
              key: addresses
        - name: SERVER_CITIES
          value: "Seattle WA"
        - name: SERVER_COUNTRIES
          value: "USA"
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/Los_Angeles"
        - name: DOT
          value: "on"
        # Let gluetun use its default DNS configuration
        - name: FIREWALL_OUTBOUND_SUBNETS
          value: "192.168.1.0/24"  # Allow local network access
        - name: FIREWALL_INPUT_PORTS
          value: "9091"  # Transmission web UI
        ports:
        - containerPort: 9091
          name: transmission
        - containerPort: 51820
          name: wireguard
          protocol: UDP
        volumeMounts:
        - name: gluetun-config
          mountPath: /gluetun
        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          exec:
            command:
              - /gluetun-entrypoint
              - healthcheck
          initialDelaySeconds: 30
          periodSeconds: 30
          
      # Transmission container
      - name: transmission
        image: linuxserver/transmission
        # Share the network namespace with gluetun
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/Los_Angeles"
        - name: TRANSMISSION_WEB_UI
          value: "transmission-web-control"
        volumeMounts:
        - name: transmission-config
          mountPath: /config
        - name: media
          mountPath: /media
        - name: downloads
          mountPath: /downloads
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
            
      volumes:
      - name: gluetun-config
        emptyDir: {}
      - name: transmission-config
        hostPath:
          path: /storage/docker_volumes/transmission
          type: DirectoryOrCreate
      - name: media
        hostPath:
          path: /storage/media
          type: Directory
      - name: downloads
        hostPath:
          path: /storage/downloads
          type: Directory