apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: download
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/poiley/rinzler.git
    targetRevision: HEAD
    path: k8s/download
  destination:
    server: https://kubernetes.default.svc
    namespace: download
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true