apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-exporters
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/poiley/rinzler
    targetRevision: HEAD
    path: k8s/monitoring/exporters
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true