apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: network-services
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/poiley/rinzler.git
    targetRevision: HEAD
    path: k8s/network-services
  destination:
    server: https://kubernetes.default.svc
    namespace: network-services
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true