apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
type: Opaque
stringData:
  # Default admin password is 'admin' - CHANGE THIS IN PRODUCTION
  admin.password: "$2a$10$rBZDlchREt5PGFhO9.9VJ.Ay4LjWCCaHiRvsMGMFSFpCLTeQKU0fC"
  admin.passwordMtime: "2025-01-01T00:00:00Z"
  server.secretkey: "my_super_secret_key_change_me"