apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
type: Opaque
stringData:
  admin.password: ${ARGOCD_ADMIN_PASSWORD_HASH}
  server.secretkey: ${ARGOCD_SERVER_SECRET_KEY}