apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mylar
  namespace: download
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: mylar.rinzler.grid
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mylar
            port:
              number: 8090
