services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    ports:
      - "8081:80/tcp"
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      TZ: ${TZ}
      WEBPASSWORD: ${PIHOLE_PASSWORD}
      RATE_LIMIT: '0/0'
    volumes:
      - '/storage/docker_volumes/pihole/etc-pihole:/etc/pihole'
      - '/storage/docker_volumes/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped