services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: vpn
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - SERVER_CITIES=Seattle WA
      - SERVER_COUNTRIES=USA
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOT=on
    dns:
      - 194.242.2.2  # Mullvad DNS
      - 10.64.0.1    # Gluetun internal DNS for VPN resolution
    ports:
      - 9091:9091    # Transmission Web UI
      - 51820:51820

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - TRANSMISSION_WEB_UI=transmission-web-control
    volumes:
      - /storage/media:/media
      - /storage/downloads:/downloads
    depends_on:
      - gluetun
    network_mode: "service:gluetun"  # Routes all traffic through gluetun
